<a href="https://colab.research.google.com/github/nebeh/dl_guu/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22start_torch_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Базовые конструкции pytorch**

In [ ]:
import torch


Базовой единице для torch является тензор (многомерный массив). 

In [ ]:
a = torch.tensor([1,2])
print(a.size())
print(a.dtype)
b = torch.tensor([[0,1],[-1,2]])
b

torch.Size([2])
torch.int64


tensor([[ 0,  1],
        [-1,  2]])

Типом данных можно управлять при задании тензора

In [ ]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned


torch.ByteTensor

In [ ]:
x = torch.HalfTensor([[1,2],[4,0.5]]) 
x


tensor([[1.0000, 2.0000],
        [4.0000, 0.5000]], dtype=torch.float16)

Изменение типа

In [ ]:
x.type_as(torch.DoubleTensor())

tensor([[1.0000, 2.0000],
        [4.0000, 0.5000]], dtype=torch.float64)

Можно задать тензор не используя конкретных значений, а только размер


In [ ]:
x = torch.DoubleTensor(2,3,2)
x


tensor([[[4.6452e-310, 1.0610e-312],
         [1.0186e-312, 9.5490e-313],
         [1.1883e-312, 1.0398e-312]],

        [[1.2308e-312, 1.2095e-312],
         [1.0610e-312, 9.7612e-313],
         [1.1034e-312, 1.1247e-312]]], dtype=torch.float64)

Тензоры специального вида (случайные числа, нулевой, единичный и т.д.)

In [ ]:
z = torch.zeros(2,3)
print(z)
o = torch.ones(3,1)
print(o)
e = torch.eye(3,3)
print(e)
x = torch.randn(100,1)



tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1.],
        [1.],
        [1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Функции: определяются на каждом элементе тензора (поэлементно)

In [ ]:
y = torch.tensor([[1.1, 2.2, 0.2]])
print(y.sin())
print(y.pow(2))


tensor([[0.8912, 0.8085, 0.1987]])
tensor([[1.2100, 4.8400, 0.0400]])


Арифметические операции (выполняются поэлементно)

In [ ]:
x = torch.tensor([[1,2],[0, 3]])
y = torch.tensor([[0, -1], [1,1]])
print(x + y)
print(x.add(y))
print(x*y)
print(x-y)


tensor([[1, 1],
        [1, 4]])
tensor([[1, 1],
        [1, 4]])
tensor([[ 0, -2],
        [ 0,  3]])
tensor([[ 1,  3],
        [-1,  2]])


Операции линейной алгебры (матричное умножение)

In [ ]:
print(x@y)
print(x.mm(y))


tensor([[2, 1],
        [3, 3]])
tensor([[2, 1],
        [3, 3]])


Логические операции


In [ ]:
x = torch.randn(1,5)
print(x)
print(x >0)

tensor([[ 0.2534,  0.0376, -0.0114, -0.0163, -1.0404]])
tensor([[ True,  True, False, False, False]])


In [ ]:
print(x[x>0])


tensor([0.2534, 0.0376])


Функции статистики

In [ ]:
x = torch.randn(4,3)
print(x)

tensor([[ 1.1537,  0.0208,  0.7959],
        [ 0.8143,  0.5381,  0.3858],
        [-1.0283, -0.4781,  0.0129],
        [-0.6155,  0.2144, -0.5494]])


In [ ]:
print(x.mean())
print(x.mean(axis=0))
print(x.mean(0))

tensor(0.1054)
tensor([0.0810, 0.0738, 0.1613])
tensor([0.0810, 0.0738, 0.1613])


Преобразование numpy -> torch -> torch

In [ ]:
import numpy as np
x = np.random.randn(2,3)
y = torch.from_numpy(x)
z = y.numpy
